spring:
  application:
    name: incloo-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  mvc:
    log-resolved-exception: false

server:
  port: ${SERVER_PORT:0}
  error:
    include-stacktrace: NEVER

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:

    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVICE_NAME:localhost}:8761/eureka
