spring:
  application:
    name: incloo-api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedMethods: "*"
            allowedOrigins: "*"
      routes:
        - id: incloo-api
          uri: lb://incloo-api
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: forward:/fallback

server:
  port: ${SERVER_PORT:8763}
  error:
    include-stacktrace: NEVER

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
    service-url:
      defaultZone: http://${EUREKA_SERVICE_NAME:localhost}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 10
        minimumNumberOfCalls: 15
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
        slidingWindowSize: 15
        slidingWindowType: COUNT_BASED
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 50
        waitDurationInOpenState: 5s
  timelimiter:
    configs:
      default:
        timeoutDuration: 20s
    instances:
      fallback:
        baseConfig: default
